#167373681 A user should be able to see a home page
eyieko/landville-frontend pull request #15
Opened 2019-07-18 14:55 UTC by JamesMudidi

## Description ##
- A user needs to be welcomed by a friendly home page.

## Type of change ##
Please select the relevant option
- [ ] Bug fix(a non-breaking change which fixes an issue)
- [x] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of a feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [ ] Integration test
- [ ] unit test

## Checklist: ##
- [ ] My code follows the style guidelines of this project
- [ ] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

## Related Pivotal Tracker stories ##
[#167373681](https://www.pivotaltracker.com/story/show/167373681)

2019-07-24 12:22 UTC, CryceTruly reviewed
Hello @JamesMudidi, could you please fix the failing tests such we can be able to run and understand the test behavior.

2019-07-24 12:23 UTC, CryceTruly requested changes

2019-07-24 12:23 UTC, CryceTruly commented on src/app/pages/home/home.component.html
> +<app-footer></app-footer>
@JamesMudidi let us remember to leave a blank line here

2019-07-24 12:23 UTC, CryceTruly commented on src/app/pages/home/home.component.scss
> +
@JamesMudidi let us remember to leave a blank line here

2019-07-30 21:22 UTC, Victoradukwu requested changes
@JamesMudidi Please work on the coverage drop and the merge conflicts.

2019-08-01 06:29 UTC, Genza999 approved these changes
LGTM, Great work James, Like the responsiveness on the UI.

2019-08-01 07:12 UTC, CryceTruly requested changes

2019-08-01 07:12 UTC, CryceTruly commented on src/app/components/footer/footer.component.html
> +</footer>
Good work @JamesMudidi, Please leave a blank line here

2019-08-01 07:12 UTC, CryceTruly commented on src/app/pages/home/home.component.scss
> +.page-header {
Good work @JamesMudidi, I notice the background image takes really long to load, could you minify it and use a minified version of it for faster rendering., You can check if this website can help https://tinypng.com/

2019-08-01 08:14 UTC, MandelaK reviewed
Nice implementation James, I would however suggest that you reduce using inline styles and instead give your elements classes for styling just so that concerns are separated ... you could also make use of bootstrap classes to change things like margins and padding instead of the inline styles ...

Also, please avoid using relative imports because they are really hard to read and edit should changes be necessary

2019-08-01 08:14 UTC, MandelaK commented on src/app/layouts/auth-layout/auth-layout.module.ts
>  import { LoginFormComponent } from '../../pages/login/login-form/login-form.component';
Please use absolute imports ... Relative imports are really hard to read and hard to edit should there be changes required later on

2019-08-01 09:03 UTC, CryceTruly approved these changes
LGTM

2019-08-01 12:55 UTC, MandelaK approved these changes
Good work James ... The UI looks stunning

2019-08-01 14:05 UTC, Victoradukwu approved these changes
LGTM

2019-08-01 14:08 UTC, merged