167528341 Add access control to App routes
eyieko/landville-frontend pull request #18
Opened 2019-08-01 06:09 UTC by CryceTruly

## Description ##
- Add access control to routes based on login status

## Type of change ##
Please select the relevant option
- [ ] Bug fix(a non-breaking change which fixes an issue)
- [x] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of a feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [ ] Integration test
- [x] unit test

## Checklist: ##
- [x] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

## Related Pivotal Tracker stories ##
[#167528341](https://www.pivotaltracker.com/story/show/167528341)

2019-08-05 15:16 UTC, patrickf949 reviewed
Great work sofar @CryceTruly 
The route protection on this seems solid.
However, there are 2 navbars upon login
Please work on this.

2019-08-06 05:04 UTC, Victoradukwu reviewed
Hey, @CryceTruly This is really great work. Kindly resolve the concern raised by @patrickf949. It is still there.

2019-08-06 06:33 UTC, CryceTruly commented
> Hey, @CryceTruly This is really great work. Kindly resolve the concern raised by @patrickf949. It is still there.

Thanks, @Victoradukwu, I have worked on that.

2019-08-06 06:33 UTC, CryceTruly commented
> Great work sofar @CryceTruly
> The route protection on this seems solid.
> However, there are 2 navbars upon login
> Please work on this.

Thanks, @patrickf949, I have worked on that.

2019-08-06 08:56 UTC, JamesMudidi reviewed
@CryceTruly, This is awesome work.
I noticed that we have two footers on the landing page.
could this be worked on? Thanks

2019-08-06 09:40 UTC, CryceTruly commented
> @CryceTruly, This is awesome work.
> I noticed that we have two footers on the landing page.
> could this be worked on? Thanks

Thanks, James, I have worked on this.

2019-08-06 12:26 UTC, patrickf949 approved these changes
LGTM

2019-08-06 14:38 UTC, Victoradukwu approved these changes
LGTM

2019-08-08 07:34 UTC, JamesMudidi requested changes

2019-08-08 07:34 UTC, JamesMudidi commented on src/app/guards/no-auth.guard.spec.ts
> +		'should ...',
Hey @CryceTruly, I am not sure what this is dong here.
can you shine some more light to it

2019-08-08 07:49 UTC, JamesMudidi approved these changes
LGTM

2019-08-08 09:55 UTC, bl4ck4ndbr0wn approved these changes
Great Job.
LGTM

2019-08-08 09:56 UTC, bl4ck4ndbr0wn commented
Try to resolve the merge conflicts.

2019-08-16 06:59 UTC, malep2007 approved these changes

2019-08-16 06:59 UTC, merged