#167204518 Fix workspace error on boilerplate
eyieko/landville-frontend pull request #5
Opened 2019-07-10 16:49 UTC by akram256

## Description ##
When trying to run the server, an error of  `landville-frontend could not be found in the workspace` is thrown. This PR corrects the spelling errors of the workspace in the angular.json file
## Type of change ##
Please select the relevant option
- [x] Bug fix(a non-breaking change which fixes an issue)
- [ ] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [ ] Integration test
- [ ] unit test

## Checklist: ##
- [x] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

## Related Pivotal Tracker stories ##
[#167204518](https://www.pivotaltracker.com/story/show/167204518)

2019-07-10 17:24 UTC, MandelaK approved these changes
Good job

2019-07-10 18:47 UTC, BrianSerem approved these changes

2019-07-10 18:49 UTC, kelvinndmo approved these changes

2019-07-11 05:32 UTC, joelethan approved these changes

2019-07-11 05:58 UTC, joelethan requested changes
@akram256, We have more places in the code that have  `landvile` instead of `landville`. It would be nice to also change them in order to have uniformity. These places are `README.md`,`karma.conf.js` and in `src/index.html`.

2019-07-11 08:02 UTC, joelethan approved these changes

2019-07-11 08:03 UTC, patrickf949 approved these changes

2019-07-11 12:30 UTC, merged